const fs = require('node:fs');
const path = require('node:path');
const { randomUUID } = require('node:crypto');
const { z } = require('../../frontend/node_modules/zod');
if (!process.env.DATABASE_URL || new URL(process.env.DATABASE_URL).hostname !== '127.0.0.1') throw new Error('Use an isolated local database');
process.env.NODE_ENV = 'test';
const { PrismaService } = require('../dist/src/prisma/prisma.service');
const db = new PrismaService();
const output = path.resolve(__dirname, '../../output/playwright/student-changes-qa-2026-10-06');
const fixture = JSON.parse(fs.readFileSync(path.join(output, 'fixtures.json')));
const base = 'http://localhost:3004/api/v1';
const checks = [];
const password = fixture.password;
const profileSchema = z.object({ userId: z.string(), preferredHours: z.array(z.number().int().min(0).max(23)), timezone: z.string() });
const clockSchema = z.object({ serverNow: z.iso.datetime(), meetingStartedAt: z.iso.datetime().nullable(), warningAt: z.iso.datetime().nullable(), meetingEndsAt: z.iso.datetime().nullable(), status: z.string(), expired: z.boolean() });
async function check(name, endpoint, method, body, token, expected, predicate = () => true) {
  const response = await fetch(base + endpoint, { method, headers: { 'Content-Type': 'application/json', ...(token ? { Authorization: `Bearer ${token}` } : {}) }, body: body === undefined ? undefined : JSON.stringify(body) });
  const data = await response.json();
  const passed = [expected].flat().includes(response.status) && response.headers.get('content-type').includes('application/json') && predicate(data);
  checks.push({ name, endpoint, expected, actual: response.status, passed, ...(passed ? {} : { response: data }) });
  console.log(`${passed ? 'PASS' : 'FAIL'} ${name}: ${response.status}`);
  return data;
}
async function run() {
  const admin = await check('Admin login remains available', '/auth/login', 'POST', { email: 'admin@ilmconnect.com', password: 'ilmconnect123' }, undefined, 201);
  const registration = { email: `feature-qa-${randomUUID()}@example.test`, password, fullName: 'QA Availability Student', phone: '000000000', country: 'Sri Lanka', timezone: 'Asia/Colombo', role: 'STUDENT', preferredHours: [13, 10, 12, 11], gender: 'MALE', dateOfBirth: '2000-01-01' };
  for (const dateOfBirth of ['2999-01-01', '2000-02-30', '0000-01-01', 'not-a-date', '2000-1-1']) await check(`Registration rejects date of birth ${dateOfBirth}`, '/auth/register', 'POST', { ...registration, dateOfBirth }, undefined, 400);
  await check('Registration rejects invalid gender', '/auth/register', 'POST', { ...registration, gender: 'invalid' }, undefined, 400);
  for (const hours of [[], [-1], [24], [10.5], [10, 10], ['10'], null, 'morning']) await check(`Registration rejects hours ${JSON.stringify(hours)}`, '/auth/register', 'POST', { ...registration, preferredHours: hours }, undefined, 400);
  const registered = await check('Register student with availability', '/auth/register', 'POST', registration, undefined, 201);
  const login = await check('New student can log in', '/auth/login', 'POST', { email: registration.email, password }, undefined, 201);
  const userId = login.user.id;
  const token = login.token;
  await check('Demographics persist on authenticated account', '/auth/me', 'GET', undefined, token, 200, data => data.gender === 'MALE' && data.dateOfBirth?.startsWith('2000-01-01'));
  await check('Hours sorted and persisted', '/profile/student', 'GET', undefined, token, 200, data => profileSchema.safeParse(data).success && JSON.stringify(data.preferredHours) === '[10,11,12,13]');
  const tickets = await check('Registration creates exactly one pending assignment request', '/support/my-tickets', 'GET', undefined, token, 200, data => data.filter(row => row.type === 'STUDENT_REGISTRATION' && row.status === 'PENDING').length === 1);
  const ticket = tickets.find(row => row.type === 'STUDENT_REGISTRATION');
  for (const hours of [[], [-1], [24], [10.5], [10, 10], ['10'], null]) await check(`Profile rejects hours ${JSON.stringify(hours)}`, '/profile/student', 'PUT', { preferredHours: hours }, token, 400);
  await check('Student cannot assign own lecturer', `/admin/requests/${ticket.id}/assign-lecturer`, 'POST', { lecturerId: fixture.lecturer.id }, token, 403);
  await db.lecturerProfile.update({ where: { userId: fixture.lecturer.id }, data: { hourlyAvailabilityJson: [18, 19] } });
  await check('Assignment rejects nonoverlapping shift', `/admin/requests/${ticket.id}/assign-lecturer`, 'POST', { lecturerId: fixture.lecturer.id }, admin.token, 400);
  await db.lecturerProfile.update({ where: { userId: fixture.lecturer.id }, data: { hourlyAvailabilityJson: Array.from({ length: 24 }, (_, i) => i) } });
  await check('Admin assignment succeeds for matching shift', `/admin/requests/${ticket.id}/assign-lecturer`, 'POST', { lecturerId: fixture.lecturer.id }, admin.token, 201, data => data.assignedLecturerId === fixture.lecturer.id);
  await check('Resolved assignment cannot be repeated', `/admin/requests/${ticket.id}/assign-lecturer`, 'POST', { lecturerId: fixture.lecturer.id }, admin.token, 400);
  await check('Student sees resolved assignment', '/support/my-tickets', 'GET', undefined, token, 200, data => data.find(row => row.id === ticket.id)?.status === 'RESOLVED');
  await check('Assignment preserves lecturer privacy', '/profile/student', 'GET', undefined, token, 200, data => !data.assignedLecturer?.payoutDetails && !data.assignedLecturer?.payoutMethod);
  await check('Availability edit persists independently of assignment', '/profile/student', 'PUT', { preferredHours: [18, 19, 20, 21] }, token, 200, data => data.assignedLecturerId === fixture.lecturer.id && data.preferredHours.length === 4);
  await check('Student cannot fake registration requests', '/support/request', 'POST', { type: 'STUDENT_REGISTRATION', reason: 'Fake registration' }, token, 400);
  const change = await check('Lecturer-change support request remains available', '/support/request', 'POST', { type: 'LECTURER_CHANGE', reason: 'QA change request' }, token, 201);
  await check('Student cannot resolve assignment request', `/support/tickets/${change.id}/messages`, 'POST', { message: 'Resolve it', newStatus: 'RESOLVED' }, token, 403);
  await check('Unstarted clock has complete nullable contract', `/livekit/clock/${fixture.upcoming.id}`, 'GET', undefined, fixture.student.token, 200, data => clockSchema.safeParse(data).success && data.meetingStartedAt === null);
  await check('Outsider cannot read meeting clock', `/livekit/clock/${fixture.upcoming.id}`, 'GET', undefined, fixture.outsider.token, 403);
  await check('Student cannot start timer', `/livekit/start/${fixture.upcoming.id}`, 'POST', {}, fixture.student.token, 403);
  await check('Outsider cannot start timer', `/livekit/start/${fixture.upcoming.id}`, 'POST', {}, fixture.outsider.token, 403);
  await check('Completed meeting timer cannot start', `/livekit/start/${fixture.completed.id}`, 'POST', {}, fixture.lecturer.token, 400);
  await check('Canceled meeting timer cannot start', `/livekit/start/${fixture.canceled.id}`, 'POST', {}, fixture.lecturer.token, 400);
  const started = await check('Lecturer starts authoritative timer', `/livekit/start/${fixture.upcoming.id}`, 'POST', {}, fixture.lecturer.token, 201, data => clockSchema.safeParse(data).success && data.status === 'IN_PROGRESS' && Date.parse(data.meetingEndsAt) - Date.parse(data.meetingStartedAt) === 45 * 60000 && Date.parse(data.warningAt) - Date.parse(data.meetingStartedAt) === 40 * 60000);
  await check('Restart call does not reset timer', `/livekit/start/${fixture.upcoming.id}`, 'POST', {}, fixture.lecturer.token, 201, data => data.meetingStartedAt === started.meetingStartedAt);
  await db.session.update({ where: { id: fixture.upcoming.id }, data: { meetingStartedAt: new Date(Date.now() - 40 * 60000 - 5000) } });
  await check('40-minute lesson gets extension, not completion', `/livekit/clock/${fixture.upcoming.id}`, 'GET', undefined, fixture.student.token, 200, data => !data.expired && data.status === 'IN_PROGRESS' && Date.parse(data.warningAt) < Date.parse(data.serverNow) && Date.parse(data.meetingEndsAt) > Date.parse(data.serverNow));
  await db.session.update({ where: { id: fixture.upcoming.id }, data: { meetingStartedAt: new Date(Date.now() - 46 * 60000) } });
  await check('45-minute expiry completes session', `/livekit/clock/${fixture.upcoming.id}`, 'GET', undefined, fixture.student.token, 200, data => data.expired && data.status === 'COMPLETED');
  await check('Expired meeting cannot obtain new token', `/livekit/token/${fixture.upcoming.id}`, 'GET', undefined, fixture.student.token, 400);
  await db.session.update({ where: { id: fixture.upcoming.id }, data: { meetingStartedAt: null, status: 'SCHEDULED' } });
  await db.subscription.create({ data: { studentId: userId, tier: 'Standard', status: 'ACTIVE', currentPeriodStart: new Date(Date.now()-86400000), currentPeriodEnd: new Date(Date.now()+14*86400000), lkrAmount: 0, fxRateApplied: 1 } });
  const breakStart = new Date(Date.now()+4*86400000);
  breakStart.setHours(10,0,0,0);
  const neighbor = await db.session.create({ data: { studentId: fixture.outsider.id, lecturerId: fixture.lecturer.id, startsAt: breakStart, endsAt: new Date(+breakStart+40*60000), status: 'SCHEDULED' } });
  for (const minutes of [49,50]) {
    const startsAt = new Date(+breakStart+minutes*60000);
    await db.availabilitySlot.create({ data: { lecturerId: fixture.lecturer.id, startsAt, endsAt: new Date(+startsAt+40*60000), status: 'OPEN' } });
  }
  await check('Nine-minute lecturer break rejected through API', '/bookings', 'POST', { lecturerId: fixture.lecturer.id, startsAt: new Date(+breakStart+49*60000).toISOString() }, token, 400, data => /10 minutes/.test(data.message));
  const booked = await check('Exactly ten-minute lecturer break accepted', '/bookings', 'POST', { lecturerId: fixture.lecturer.id, startsAt: new Date(+breakStart+50*60000).toISOString() }, token, 201, data => Date.parse(data.endsAt)-Date.parse(data.startsAt)===40*60000);
  await check('Student receives own booking confirmation', '/notifications', 'GET', undefined, token, 200, data => data.some(row => row.type === 'BOOKING_CONFIRMED' && row.payloadJson?.sessionId === booked.id));
  await check('Lecturer receives student booking confirmation', '/notifications', 'GET', undefined, fixture.lecturer.token, 200, data => data.some(row => row.type === 'BOOKING_CONFIRMED' && row.payloadJson?.sessionId === booked.id));
  await db.session.delete({where:{id:neighbor.id}});
  await check('Currency API retains five-code contract', '/subscriptions/currencies', 'GET', undefined, undefined, 200, data => Array.isArray(data) && data.length === 5 && data.every(row => ['LKR', 'USD', 'GBP', 'EUR', 'AUD'].includes(row.code) && typeof row.available === 'boolean' && typeof row.stale === 'boolean'));
  const plans = await check('Unconfigured LKR prices are explicitly unavailable; USD preserved', '/subscriptions/plans', 'GET', undefined, undefined, 200, data => data.length === 6 && data.every(plan => (plan.monthlyLkr === null || plan.monthlyLkr > 0) && plan.prices.LKR === plan.monthlyLkr && plan.prices.USD === plan.monthlyUsd && ['GBP', 'EUR', 'AUD'].every(code => plan.prices[code] === null || plan.prices[code] > 0)));
  await check('Students cannot edit plan prices', '/subscriptions/plans', 'PATCH', { prices: plans.map(plan => ({ id: plan.id, monthlyUsd: plan.monthlyUsd, monthlyLkr: plan.monthlyLkr })) }, fixture.student.token, 403);
  const prices = plans.map(plan => ({ id: plan.id, monthlyUsd: plan.monthlyUsd, monthlyLkr: plan.tier === 'Standard' ? 12000 : 18000 }));
  await check('Admin price update rejects missing plans', '/subscriptions/plans', 'PATCH', { prices: prices.slice(1) }, admin.token, 400);
  await check('Admin price update rejects zero prices', '/subscriptions/plans', 'PATCH', { prices: prices.map((row, i) => i ? row : { ...row, monthlyLkr: 0 }) }, admin.token, 400);
  await check('Admin price update rejects duplicate plan IDs', '/subscriptions/plans', 'PATCH', { prices: prices.map((row, i) => i ? row : { ...row, id: prices[1].id }) }, admin.token, 400);
  await check('Admin cannot underprice local Fast Track', '/subscriptions/plans', 'PATCH', { prices: prices.map(row => row.id.includes('fast-track') ? { ...row, monthlyLkr: 1000 } : row) }, admin.token, 400);
  await check('Admin configures independent regional prices', '/subscriptions/plans', 'PATCH', { prices }, admin.token, 200, data => data.every(plan => plan.prices.LKR === (plan.tier === 'Standard' ? 12000 : 18000) && plan.prices.USD === plan.monthlyUsd));
  await check('Checkout still fails honestly without payment integration', '/subscriptions', 'POST', { tier: 'Standard' }, token, 501);
  fs.writeFileSync(path.join(output, 'feature-fixture.json'), JSON.stringify({ userId, email: registration.email, password, token, ticketId: ticket.id }), { mode: 0o600 });
}
run().catch(error => { console.error(error); process.exitCode = 1; }).finally(async () => {
  fs.writeFileSync(path.join(output, 'feature-api-results.json'), JSON.stringify({ date: '2026-10-06', checks, passed: checks.filter(row => row.passed).length, failed: checks.filter(row => !row.passed).length }, null, 2));
  if (checks.some(row => !row.passed)) process.exitCode = 1;
  await db.$disconnect();
});
