const assert = require('node:assert/strict');
const fs = require('node:fs/promises');
const path = require('node:path');
const crypto = require('node:crypto');
process.env.DATABASE_URL = process.env.ATTENDANCE_QA_DATABASE_URL || 'postgresql://attendance_qa@127.0.0.1:55448/attendance_qa';
if (!/^postgresql:\/\/[^/]*@(localhost|127\.0\.0\.1):/.test(process.env.DATABASE_URL)) throw new Error('Use an isolated local QA database');
process.env.NODE_ENV = 'test';
const { Test } = require('@nestjs/testing');
const { ValidationPipe } = require('@nestjs/common');
const { AppModule } = require('../dist/src/app.module');
const { PrismaService } = require('../dist/src/prisma/prisma.service');
const { LivekitService } = require('../dist/src/livekit/livekit.service');
const { EmailNotificationService } = require('../dist/src/notification/email-notification.service');
const { WhatsAppNotificationService } = require('../dist/src/notification/whatsapp-notification.service');
const { AccessToken, WebhookReceiver } = require('livekit-server-sdk');
const { chromium, expect } = require(process.env.QA_PLAYWRIGHT_PATH || '/Users/humaid/.npm/_npx/e41f203b7505f1fb/node_modules/playwright/test');
const { z } = require('../../frontend/node_modules/zod');
const bcrypt = require('bcrypt');
const api = 'http://localhost:3017/api/v1', web = 'http://localhost:3007';
const out = path.resolve(__dirname, '../../output/student-attendance-qa');
const results = [], users = [], sessions = [], closedRooms = [], deliveries = [], errors = [];
const password = crypto.randomUUID() + '!aA1';
const webhookSecret = crypto.randomUUID() + crypto.randomUUID();
const receiver = new WebhookReceiver('attendance-qa-key', webhookSecret);
const roomPresence = new Map();
let app, db, browser, configured = false, providerDown = false, failClose = false, delayClose = false, closeEntered = false, releaseClose;
const schema = z.object({ serverNow: z.iso.datetime(), status: z.string(), studentJoinedAt: z.iso.datetime().nullable(), studentPresent: z.boolean().nullable(), detectionAvailable: z.boolean(), promptAt: z.iso.datetime().nullable(), shouldPrompt: z.boolean() });
function passed(name) { results.push({ name, passed: true }); console.log('PASS ' + name); }
async function request(endpoint, user, method = 'GET', body, status = 200) {
  const response = await fetch(api + endpoint, { method, headers: { 'Content-Type': 'application/json', ...(user ? { Authorization: 'Bearer ' + user.token } : {}) }, body: body === undefined ? undefined : JSON.stringify(body) });
  const data = await response.json();
  assert.equal(response.status, status, endpoint + ': ' + JSON.stringify(data));
  assert.match(response.headers.get('content-type'), /application\/json/);
  return data;
}
async function person(role, name) {
  const data = { email: `attendance-${crypto.randomUUID()}@example.test`, passwordHash: await bcrypt.hash(password, 4), role, status: 'ACTIVE' };
  if (role === 'LECTURER') data.lecturerProfile = { create: { fullName: name, bio: 'QA', qualifications: 'QA', languages: ['English'], specializations: ['Quran'], hourlyAvailabilityJson: [10], payoutMethod: 'bank_transfer', payoutDetails: 'QA', status: 'ACTIVE' } };
  if (role === 'STUDENT') data.studentProfile = { create: { fullName: name, phone: '+94771234567', country: 'Sri Lanka', timezone: 'Asia/Colombo', preferredLanguage: 'English', learningGoals: 'QA' } };
  const user = await db.user.create({ data }); users.push(user.id);
  const login = await request('/auth/login', null, 'POST', { email: user.email, password }, 201);
  return { ...user, token: login.token };
}
async function session(student, lecturer, minutes = 15, extra = {}) {
  const startsAt = new Date(Date.now() - 30 * 60000);
  const row = await db.session.create({ data: { studentId: student.id, lecturerId: lecturer.id, startsAt, endsAt: new Date(+startsAt + 40 * 60000), status: 'IN_PROGRESS', livekitRoomName: 'qa-attendance-' + crypto.randomUUID(), meetingStartedAt: new Date(Date.now() - minutes * 60000), ...extra } });
  sessions.push(row.id); return row;
}
async function login(page, user, role) {
  await page.goto(web + '/auth/signin');
  await page.getByRole('textbox', { name: 'Email address' }).fill(user.email);
  await page.getByRole('textbox', { name: 'Password', exact: true }).fill(password);
  await page.getByRole('button', { name: 'Log in', exact: true }).click();
  await page.waitForURL(`**/${role}/dashboard`);
}
async function webhook(row, user, event = 'participant_joined', createdAt = Math.floor(Date.now() / 1000), signed = true, contentType = 'application/webhook+json') {
  const body = JSON.stringify({ event, room: { name: row.livekitRoomName }, participant: { identity: 'student:' + user.id }, createdAt: String(createdAt), id: crypto.randomUUID() });
  const token = new AccessToken('attendance-qa-key', webhookSecret);
  token.sha256 = crypto.createHash('sha256').update(body).digest('base64');
  const response = await fetch(api + '/livekit/webhook', { method: 'POST', headers: { 'Content-Type': contentType, ...(signed ? { Authorization: await token.toJwt() } : {}) }, body });
  return { response, data: await response.json(), body, token };
}
async function run() {
  await fs.mkdir(out, { recursive: true });
  const module = await Test.createTestingModule({ imports: [AppModule] }).overrideProvider(LivekitService).useValue({
    isConfigured: () => configured, getRoomName: id => 'qa-' + id,
    studentIsPresent: async room => { if (providerDown) throw new Error('QA provider unavailable'); return roomPresence.get(room) || false; },
    endRoom: async room => { if (failClose) throw new Error('QA close failed'); if (delayClose) { closeEntered = true; await new Promise(resolve => { releaseClose = resolve; }); } closedRooms.push(room); roomPresence.set(room, false); },
    receiveWebhook: (body, authorization) => receiver.receive(body, authorization),
    generateToken: async () => ({ token: 'sim_qa', wsUrl: '', isSimulation: true }),
  }).overrideProvider(EmailNotificationService).useValue({ buildBookingEmail: () => ({ subject: 'QA attendance', htmlContent: '', textContent: '' }), sendEmail: async payload => { deliveries.push(payload); return true; } })
    .overrideProvider(WhatsAppNotificationService).useValue({ buildBookingMessage: () => 'QA attendance', sendWhatsApp: async () => true }).compile();
  app = module.createNestApplication({ logger: false, rawBody: true });
  app.use('/api/v1/livekit/webhook', require('express').raw({ type: 'application/webhook+json' }));
  app.setGlobalPrefix('api/v1'); app.use(require('cookie-parser')()); app.enableCors({ origin: web, credentials: true });
  app.useGlobalPipes(new ValidationPipe({ whitelist: true, transform: true, forbidNonWhitelisted: true }));
  await app.listen(3017); db = app.get(PrismaService);
  const lecturer = await person('LECTURER', 'QA Attendance Lecturer'), other = await person('LECTURER', 'QA Other Lecturer');
  const student = await person('STUDENT', 'QA Attendance Student'), foreign = await person('STUDENT', 'QA Other Student'), admin = await person('ADMIN', 'QA Admin');
  await db.studentProfile.update({ where: { userId: student.id }, data: { assignedLecturerId: lecturer.id } });
  await db.subscription.create({ data: { studentId: student.id, tier: 'Standard', status: 'ACTIVE', currentPeriodStart: new Date(Date.now() - 86400000), currentPeriodEnd: new Date(Date.now() + 30 * 86400000), lkrAmount: 0, fxRateApplied: 1 } });
  const noShow = await session(student, lecturer);
  await request('/livekit/attendance/' + noShow.id, null, 'GET', undefined, 401);
  await request('/livekit/attendance/' + noShow.id, other, 'GET', undefined, 403);
  await request('/livekit/attendance/' + noShow.id, foreign, 'GET', undefined, 403);
  await request('/livekit/attendance/' + noShow.id + '/wait', student, 'POST', {}, 403);
  await request('/livekit/attendance/' + noShow.id + '/absent', student, 'POST', {}, 403);
  await request('/livekit/attendance/' + noShow.id + '/heartbeat', lecturer, 'POST', {}, 403);
  schema.parse(await request('/livekit/attendance/' + noShow.id, admin));
  passed('Attendance contract, authentication and participant/decision permissions');
  const before = await session(student, lecturer, 14.5);
  assert.equal((await request('/livekit/attendance/' + before.id, lecturer)).shouldPrompt, false);
  await request('/livekit/attendance/' + before.id + '/absent', lecturer, 'POST', {}, 400);
  await request('/livekit/attendance/' + before.id + '/wait', lecturer, 'POST', {}, 400);
  const early = await session(student, lecturer, 20, { startsAt: new Date(Date.now() + 3600000) });
  assert.equal((await request('/livekit/attendance/' + early.id, lecturer)).shouldPrompt, false);
  passed('No prompt or absence before fifteen minutes, including early lecturer arrivals');
  assert.equal((await request('/livekit/attendance/' + noShow.id, lecturer)).shouldPrompt, true);
  await request('/livekit/token/' + noShow.id, student);
  assert.equal((await request('/livekit/attendance/' + noShow.id, lecturer)).studentJoinedAt, null);
  passed('Fifteen-minute no-show is detected and a room token alone never counts as attendance');
  const waiting = await request('/livekit/attendance/' + noShow.id + '/wait', lecturer, 'POST', {}, 201);
  assert.equal(waiting.shouldPrompt, false); assert.ok(Date.parse(waiting.promptAt) - Date.now() > 295000);
  await request('/livekit/attendance/' + noShow.id + '/absent', lecturer, 'POST', {}, 400);
  await db.session.update({ where: { id: noShow.id }, data: { attendancePromptAfter: new Date(Date.now() - 1) } });
  assert.equal((await request('/livekit/attendance/' + noShow.id, lecturer)).shouldPrompt, true);
  passed('Wait persists across requests, blocks absence during the wait, and re-prompts after five minutes');
  configured = true;
  providerDown = true;
  assert.equal((await request('/livekit/attendance/' + noShow.id, lecturer)).detectionAvailable, false);
  await request('/livekit/attendance/' + noShow.id + '/absent', lecturer, 'POST', {}, 400);
  providerDown = false;
  await request('/livekit/attendance/' + noShow.id + '/heartbeat', student, 'POST', {}, 400);
  passed('Provider failures stay unknown and client claims are checked against real room presence');
  const joined = await session(student, lecturer, 10);
  roomPresence.set(joined.livekitRoomName, true);
  const attendance = await request('/livekit/attendance/' + joined.id, lecturer);
  assert.equal(attendance.studentPresent, true); assert.ok(attendance.studentJoinedAt); assert.equal(attendance.shouldPrompt, false);
  roomPresence.set(joined.livekitRoomName, false);
  await db.session.update({ where: { id: joined.id }, data: { meetingStartedAt: new Date(Date.now() - 20 * 60000) } });
  const disconnected = await request('/livekit/attendance/' + joined.id, lecturer);
  assert.equal(disconnected.studentPresent, false); assert.equal(disconnected.shouldPrompt, false);
  await request('/livekit/attendance/' + joined.id + '/absent', lecturer, 'POST', {}, 400);
  passed('Connected students are recorded; later disconnection never turns attendance into a no-show');
  const webhookSession = await session(student, lecturer, 10);
  assert.equal((await webhook(webhookSession, student, 'participant_joined', Math.floor(Date.now() / 1000), false)).response.status, 401);
  const signed = await webhook(webhookSession, student);
  assert.equal(signed.response.status, 200); assert.ok((await db.session.findUnique({ where: { id: webhookSession.id } })).studentJoinedAt);
  const bad = await fetch(api + '/livekit/webhook', { method: 'POST', headers: { 'Content-Type': 'application/webhook+json', Authorization: await signed.token.toJwt() }, body: signed.body + ' ' });
  assert.equal(bad.status, 401);
  assert.equal((await webhook(webhookSession, student, 'participant_left', Math.floor(Date.now() / 1000), true, 'application/json')).response.status, 200);
  assert.equal((await request('/livekit/attendance/' + webhookSession.id, lecturer)).shouldPrompt, false);
  passed('Real SDK webhook verification accepts raw signed join/leave events and rejects unsigned/tampered payloads');
  failClose = true;
  await request('/livekit/attendance/' + noShow.id + '/absent', lecturer, 'POST', {}, 500);
  assert.equal((await db.session.findUnique({ where: { id: noShow.id } })).status, 'IN_PROGRESS');
  assert.equal(await db.auditLog.count({ where: { entityId: noShow.id, action: 'SESSION_STUDENT_NO_SHOW' } }), 0);
  failClose = false;
  const absent = await request('/livekit/attendance/' + noShow.id + '/absent', lecturer, 'POST', {}, 201);
  assert.equal(absent.status, 'NO_SHOW_STUDENT'); assert.ok(closedRooms.includes(noShow.livekitRoomName));
  assert.equal(await db.auditLog.count({ where: { entityId: noShow.id, action: 'SESSION_STUDENT_NO_SHOW' } }), 1);
  await request('/livekit/attendance/' + noShow.id + '/absent', lecturer, 'POST', {}, 400);
  assert.ok(deliveries.some(item => item.metadata.sessionId === noShow.id));
  assert.ok((await request('/admin/sessions', admin)).some(item => item.id === joined.id && item.studentJoinedAt));
  passed('Close failures roll back absence; successful absence closes the room, records audit, notifies and is not repeatable');
  const reset = await session(student, lecturer, 15, { startsAt: new Date(Date.now() - 2 * 3600000), endsAt: new Date(Date.now() - 80 * 60000), status: 'NO_SHOW_STUDENT', studentJoinedAt: new Date(), studentLastSeenAt: new Date(), attendancePromptAfter: new Date() });
  await request('/livekit/reopen/' + reset.id, lecturer, 'POST', {}, 201);
  const resetRow = await db.session.findUnique({ where: { id: reset.id } });
  assert.equal(resetRow.studentJoinedAt, null); assert.equal(resetRow.studentLastSeenAt, null); assert.equal(resetRow.attendancePromptAfter, null);
  await webhook(reset, student);
  assert.equal((await db.session.findUnique({ where: { id: reset.id } })).studentJoinedAt, null);
  await webhook({ ...reset, livekitRoomName: resetRow.livekitRoomName }, student);
  assert.ok((await db.session.findUnique({ where: { id: reset.id } })).studentJoinedAt);
  passed('Reopening starts a fresh attendance attempt');
  configured = false;
  await db.session.updateMany({ where: { id: { in: sessions } }, data: { status: 'CANCELED' } });

  browser = await chromium.launch({ headless: true });
  const lecturerContext = await browser.newContext({ viewport: { width: 1440, height: 1000 }, timezoneId: 'Asia/Colombo' });
  const page = await lecturerContext.newPage(); page.on('pageerror', error => errors.push(error.message));
  await login(page, lecturer, 'lecturer');
  const live = await session(student, lecturer, 14.5);
  await page.goto(web + '/lecturer/sessions/' + live.id + '/room');
  await expect(page.getByRole('status').filter({ hasText: 'Waiting for student to join' })).toBeVisible();
  const dialog = page.getByRole('dialog', { name: 'Student has not joined', exact: true });
  await expect(dialog).toBeHidden();
  await db.session.update({ where: { id: live.id }, data: { meetingStartedAt: new Date(Date.now() - 15 * 60000 - 1000) } });
  await page.evaluate(() => window.dispatchEvent(new Event('focus')));
  await expect(dialog).toBeVisible({ timeout: 15000 });
  assert.equal(await dialog.getByRole('button').count(), 2);
  await expect(dialog.getByRole('button', { name: 'Wait for a while' })).toBeFocused();
  await page.addScriptTag({ path: '/tmp/ilm-student-qa-tools/node_modules/axe-core/axe.min.js' });
  const axe = await dialog.evaluate(element => window.axe.run(element)); assert.deepEqual(axe.violations.map(item => item.id), []);
  await page.screenshot({ path: path.join(out, 'lecturer-absence-desktop.png'), animations: 'disabled' });
  await page.setViewportSize({ width: 390, height: 844 });
  assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth));
  await page.screenshot({ path: path.join(out, 'lecturer-absence-mobile.png'), animations: 'disabled' });
  await page.evaluate(() => document.documentElement.style.fontSize = '200%');
  await dialog.getByRole('button', { name: 'Mark class absent' }).scrollIntoViewIfNeeded();
  assert.ok(await dialog.evaluate(element => element.scrollWidth <= element.clientWidth));
  await page.evaluate(() => document.documentElement.style.fontSize = '');
  await page.setViewportSize({ width: 1440, height: 1000 });
  passed('Lecturer prompt appears only after fifteen minutes with exactly two buttons; mobile, zoom and axe checks pass');
  await dialog.getByRole('button', { name: 'Wait for a while' }).focus();
  await page.keyboard.press('Enter');
  await expect(dialog).toBeHidden();
  await page.reload(); await expect(page.getByRole('button', { name: 'End Session', exact: true })).toBeVisible(); await expect(dialog).toBeHidden();
  passed('Wait keeps the classroom open and stays dismissed after reload');
  await db.session.update({ where: { id: live.id }, data: { attendancePromptAfter: new Date(Date.now() - 1) } });
  await page.evaluate(() => window.dispatchEvent(new Event('focus'))); await expect(dialog).toBeVisible({ timeout: 15000 });
  const studentContext = await browser.newContext(); const studentPage = await studentContext.newPage(); studentPage.on('pageerror', error => errors.push(error.message));
  await login(studentPage, student, 'student');
  await studentPage.goto(web + '/student/courses/beginner-qaida/sessions/' + live.id + '/room');
  await expect(studentPage.getByRole('heading', { name: 'Your classroom', exact: true })).toBeVisible();
  await expect(dialog).toBeVisible();
  await studentPage.getByRole('button', { name: 'Enter classroom', exact: true }).click();
  await expect(studentPage.getByRole('button', { name: 'Leave Class', exact: true })).toBeVisible();
  await expect(dialog).toBeHidden({ timeout: 15000 });
  await expect(page.getByRole('status').filter({ hasText: 'Student joined' })).toBeVisible();
  passed('Pre-join preview does not count; actual student entry updates lecturer attendance and dismisses the prompt');
  await studentContext.close();
  await db.session.update({ where: { id: live.id }, data: { studentLastSeenAt: new Date(Date.now() - 30000) } });
  await page.evaluate(() => window.dispatchEvent(new Event('focus')));
  await expect(page.getByRole('status').filter({ hasText: 'Student joined, now disconnected' })).toBeVisible({ timeout: 15000 });
  await expect(dialog).toBeHidden();
  passed('A student who attended and later left is shown as disconnected without an absence prompt');
  await request('/bookings/' + live.id, lecturer, 'PATCH', { status: 'COMPLETED', notes: 'The student joined and practised pronunciation during this lesson.' });
  await page.waitForURL('**/lecturer/sessions', { timeout: 15000 });
  const missing = await session(student, lecturer, 15);
  await page.goto(web + '/lecturer/sessions/' + missing.id + '/room'); await expect(dialog).toBeVisible({ timeout: 15000 });
  failClose = true;
  await dialog.getByRole('button', { name: 'Mark class absent' }).click();
  await expect(dialog.getByRole('alert')).toBeVisible(); await expect(dialog).toBeVisible();
  assert.equal((await db.session.findUnique({ where: { id: missing.id } })).status, 'IN_PROGRESS');
  failClose = false;
  delayClose = true;
  await dialog.getByRole('button', { name: 'Mark class absent' }).click();
  await expect.poll(() => closeEntered).toBe(true);
  await page.getByRole('button', { name: 'End Session', exact: true, includeHidden: true }).evaluate(button => button.click());
  await expect(page.getByRole('dialog', { name: 'Lesson feedback required' })).toBeVisible();
  releaseClose(); delayClose = false;
  await page.waitForURL('**/lecturer/sessions');
  await expect(page.getByRole('dialog', { name: 'Lesson feedback required' })).toBeHidden();
  assert.equal((await db.session.findUnique({ where: { id: missing.id } })).status, 'NO_SHOW_STUDENT');
  passed('Mark class absent retries a close failure and handles a disconnect during close without leaving a completed-lesson feedback prompt');
  const onTime = await session(student, lecturer, 14);
  await page.goto(web + '/lecturer/sessions/' + onTime.id + '/room');
  await expect(page.getByRole('status').filter({ hasText: 'Waiting for student to join' })).toBeVisible();
  const onTimeContext = await browser.newContext(); const onTimePage = await onTimeContext.newPage();
  await login(onTimePage, student, 'student');
  await onTimePage.goto(web + '/student/courses/beginner-qaida/sessions/' + onTime.id + '/room');
  await onTimePage.getByRole('button', { name: 'Enter classroom', exact: true }).click();
  await expect(page.getByRole('status').filter({ hasText: 'Student joined' })).toBeVisible({ timeout: 15000 });
  await db.session.update({ where: { id: onTime.id }, data: { meetingStartedAt: new Date(Date.now() - 16 * 60000) } });
  await page.evaluate(() => window.dispatchEvent(new Event('focus')));
  const onTimeSnapshot = await request('/livekit/attendance/' + onTime.id, lecturer); assert.equal(onTimeSnapshot.shouldPrompt, false);
  await expect(dialog).toBeHidden(); await onTimeContext.close();
  await request('/bookings/' + onTime.id, lecturer, 'PATCH', { status: 'COMPLETED', notes: 'The student joined within fifteen minutes and completed their reading practice.' });
  await page.waitForURL('**/lecturer/sessions', { timeout: 15000 });
  passed('Joining within fifteen minutes prevents the lecturer prompt after the deadline');
  const adminContext = await browser.newContext({ viewport: { width: 1440, height: 1000 } }); const adminPage = await adminContext.newPage();
  await login(adminPage, admin, 'admin'); await adminPage.goto(web + '/admin/sessions');
  await expect(adminPage.getByRole('columnheader', { name: 'Student attendance' })).toBeVisible();
  await adminPage.getByRole('textbox').first().fill(missing.id);
  await expect(adminPage.getByRole('cell', { name: 'Marked absent', exact: true })).toBeVisible();
  await adminPage.screenshot({ path: path.join(out, 'admin-student-absence.png'), fullPage: true, animations: 'disabled' });
  await adminPage.getByRole('textbox').first().fill(live.id);
  await expect(adminPage.getByRole('cell', { name: /^Joined at/ })).toBeVisible();
  const adminWaiting = await session(student, lecturer, 16);
  await adminPage.reload(); await adminPage.getByRole('textbox').first().fill(adminWaiting.id);
  await expect(adminPage.getByRole('cell', { name: 'No join recorded (15+ min)', exact: true })).toBeVisible();
  const exportFile = adminPage.waitForEvent('download'); await adminPage.getByRole('button', { name: /export/i }).click();
  const download = await exportFile; const stream = await download.createReadStream(); let csv = ''; for await (const chunk of stream) csv += chunk;
  assert.ok(csv.includes('Student attendance')); assert.ok(csv.includes('No join recorded (15+ min)'));
  passed('Admin sees joined, waiting-too-long and absent states automatically; CSV includes attendance');
  assert.deepEqual(errors, []); passed('Lecturer and student browser flows produce no runtime errors');
}
run().catch(async error => { results.push({ name: 'QA execution', passed: false, error: error.stack }); console.error(error); process.exitCode = 1;
  const page = browser?.contexts()[0]?.pages()[0]; if (page) await page.screenshot({ path: path.join(out, 'failure.png'), animations: 'disabled' }); })
  .finally(async () => {
    if (browser) await browser.close();
    if (db) { await db.auditLog.deleteMany({ where: { actorId: { in: users } } }); await db.notification.deleteMany({ where: { userId: { in: users } } }); await db.user.deleteMany({ where: { id: { in: users } } }); }
    if (app) await app.close();
    await fs.mkdir(out, { recursive: true }); await fs.writeFile(path.join(out, 'results.json'), JSON.stringify(results, null, 2));
    console.log(JSON.stringify({ total: results.length, passed: results.filter(item => item.passed).length }));
  }).then(() => process.exit(process.exitCode || 0));
